version: '3.7'
services:
  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: stock_web
    container_name: stock_web
    restart: "no"
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      DEBUG: "false"
      APP_SERVER: http://app:80
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: stock_app
    container_name: stock_app
    restart: "no"
    tty: true
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
        - ./app/src:/src
  db:
    image: redis:5.0.6-alpine3.10
    restart: "no"
    container_name: dockerkvs_db
    volumes:
      - dockerkvs_redis_volume:/data

volumes:
  dockerkvs_redis_volume:
    driver: local
