version: '3.7'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: dockerkvs_app
    container_name: dockerkvs_app
    restart: "no"
    tty: true
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB: 0
  db:
    image: redis:5.0.6-alpine3.10
    restart: "no"
    container_name: dockerkvs_db
    volumes:
      - dockerkvs_redis_volume:/data

volumes:
  dockerkvs_redis_volume:
    driver: local
