version: '3.7'
services:
  apptest:
    build:
      context: ./apptest
      dockerfile: Dockerfile
    image: stock_apptest
    container_name: stock_apptest
    depends_on:
      - app
    tty: true
    environment:
      APP_HOST: app
      APP_PORT: 80
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: stock_web
    container_name: stock_web
    restart: "no"
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      DEBUG: "false"
      APP_SERVER: http://app:80
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: dockerkvs_app
    container_name: dockerkvs_app
    restart: "no"
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB: 0
  db:
    image: redis:5.0.6-alpine3.10
    restart: "no"
    container_name: dockerkvs_db
    volumes:
      - dockerkvs_redis_volume:/data

volumes:
  dockerkvs_redis_volume:
    driver: local
