version: '3.7'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: stock_app
    container_name: stock_app
    restart: "no"
    tty: true
    ports:
      - 80:80
    volumes:
        - ./app/src:/src
