version: '3.7'
services:
  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: stock_web
    container_name: stock_web
    restart: "no"
    depends_on:
      - app
    ports:
      - 3000:3000
    environment:
      DEBUG: "false"
      APP_SERVER: http://app:3000
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: stock_app
    container_name: stock_app
    restart: "no"
    tty: true
    volumes:
        - ./app/src:/src
