apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-1
spec:
  selector:
    matchLabels:
      app: go-app-1
  replicas: 1
  template:
    metadata:
      labels:
        app: go-app-1
    spec:
      containers:
      - name: go-app-1
        image: kuniaki/stock_web:220210.2312
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
